apiVersion: v1
kind: Service
metadata:
  name: camel-proxy
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: camel-proxy-tls
spec:
  selector:
    app: camel-proxy
  ports:
    - port: 8443
      targetPort: 8443